---
- hosts: all
  tasks:
  - name: Instantiating a file from a template
    template:
      src: ../templates/nginx.conf.j2
      dest: /etc/nginx.conf
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    tags: [nginx, config]